180126_wavenet_with


In [1]:
import tensorflow as tf

/home/aeatda/anaconda3/envs/proj3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)


In [29]:
indices0 = np.array([0, 1, 2]).reshape(3, 1)
indices = np.array([indices0, indices0])
depth = 4
t1 = tf.one_hot(indices, depth)  # output: [3 x 3]
# [[1., 0., 0.],
#  [0., 1., 0.],
#  [0., 0., 1.]]

In [25]:
indices = np.array([np.arange(3), np.arange(3)])
t1 = tf.one_hot(indices, depth)

In [27]:
indices

array([[0, 1, 2],
       [0, 1, 2]])

In [28]:
sess = tf.Session()
sess.run(t1)

array([[[ 1.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  0.]],

       [[ 1.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  0.]]], dtype=float32)

In [30]:
sess = tf.Session()
sess.run(t1)

array([[[[ 1.,  0.,  0.,  0.]],

        [[ 0.,  1.,  0.,  0.]],

        [[ 0.,  0.,  1.,  0.]]],


       [[[ 1.,  0.,  0.,  0.]],

        [[ 0.,  1.,  0.,  0.]],

        [[ 0.,  0.,  1.,  0.]]]], dtype=float32)

In [31]:
t2 = tf.reshape(t1, (2, -1, 4))

In [32]:
sess = tf.Session()
t1_, t2_ = sess.run([t1, t2])

In [34]:
t1_

array([[[[ 1.,  0.,  0.,  0.]],

        [[ 0.,  1.,  0.,  0.]],

        [[ 0.,  0.,  1.,  0.]]],


       [[[ 1.,  0.,  0.,  0.]],

        [[ 0.,  1.,  0.,  0.]],

        [[ 0.,  0.,  1.,  0.]]]], dtype=float32)

In [33]:
t2_

array([[[ 1.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  0.]],

       [[ 1.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  0.]]], dtype=float32)

In [35]:
t1_.shape, t2_.shape

((2, 3, 1, 4), (2, 3, 4))

In [36]:
df = pd.read_csv('../_data/combined_csv/180126_3600samp_cry386_laugh703_with_ids_mu_law.csv')

In [41]:
df

sound_id  start_idx      0      1      2      3      4      5      6  \
0       338346      18000   75.0   81.0   93.0  128.0  163.0  175.0  181.0   
1       246309      26500  195.0  189.0  181.0  174.0  168.0  168.0  170.0   
2       219433      16500   27.0   28.0   32.0   42.0   62.0  158.0  198.0   
3       211528      51500   75.0   80.0   73.0   73.0   78.0   74.0   86.0   
4       211529       7000   38.0   43.0   44.0   44.0   57.0  180.0  204.0   
5       391181       6000   71.0   33.0   28.0   42.0  187.0  182.0   53.0   
6       405204      39500  182.0  190.0  203.0  203.0  190.0  167.0   87.0   
7       259606      21000   98.0  132.0  105.0   81.0   70.0   64.0   84.0   
8       259608       9000  157.0  179.0  167.0   91.0  176.0  208.0  217.0   
9       346663      45500  190.0  201.0  206.0  203.0  180.0   61.0   42.0   
10      154427      10500  187.0  195.0  194.0  188.0  185.0  179.0  160.0   
11      154428      82500  216.0  207.0  207.0  210.0   77.0   48.0   54.0   
12      187570      41500   63.0   62.0   60.0   58.0   56.0   54.0   53.0   
13      154834      25000  197.0   55.0   68.0  206.0  178.0   73.0  192.0   
14      154441      43000   73.0   42.0   28.0   35.0   75.0  199.0  202.0   
15      154442      64500   45.0  210.0  236.0  241.0  231.0  207.0  198.0   
16      102431       3000  160.0  171.0  173.0  170.0  165.0  147.0   81.0   
17      343411      69000   35.0   36.0   41.0   49.0   63.0   99.0  159.0   
18      398552      38000   43.0   54.0   77.0   70.0   79.0  194.0  216.0   
19      259607      18000  183.0  186.0  180.0  173.0  180.0  188.0  177.0   
20      238250       1500   35.0   36.0   39.0   42.0   42.0   46.0   46.0   
21       41328      13000   71.0   66.0   62.0   61.0   64.0   69.0   73.0   
22      393769      23500   41.0   45.0   56.0   91.0  202.0  218.0  219.0   
23      408740      53000  136.0  135.0  126.0  130.0  129.0  123.0  133.0   
24      333789      38500   51.0   51.0   50.0   50.0   50.0   49.0   48.0   
25      254869      64500   61.0   57.0   56.0   56.0   56.0   57.0   57.0   
26      172738      41000   34.0   25.0   28.0   53.0  199.0  224.0  229.0   
27      319537      83000   82.0  116.0  224.0  229.0  181.0   49.0   65.0   
28      144473      67000  175.0  177.0  165.0   90.0   67.0   64.0   73.0   
29      398548      61500   35.0   39.0   49.0   98.0  192.0  190.0  186.0   
...        ...        ...    ...    ...    ...    ...    ...    ...    ...   
1059    102999       9000  181.0  184.0  183.0  178.0  167.0  143.0   98.0   
1060    162767      83000  180.0  189.0  195.0  197.0  196.0  196.0  197.0   
1061     88233      21000   50.0   56.0   66.0   79.0  111.0  167.0  180.0   
1062     93661      33000  160.0  104.0   79.0   70.0   66.0   65.0   64.0   
1063    257211      41000  188.0  186.0  181.0  181.0  184.0  187.0  189.0   
1064     64342      41500   87.0   73.0   61.0   52.0   46.0   42.0   38.0   
1065     23725      50000  104.0  103.0  100.0   97.0   95.0   93.0   92.0   
1066     19661      45500  200.0  199.0  198.0  198.0  202.0  208.0  212.0   
1067     88135      42000  181.0  166.0   80.0   62.0   96.0  191.0  148.0   
1068     76606      33000  148.0  158.0  167.0  175.0  180.0  183.0  186.0   
1069    366418      24500  204.0  202.0  187.0   86.0   56.0   53.0   63.0   
1070    367746      82000   67.0   66.0   70.0   67.0   69.0   99.0  171.0   
1071     71329      32000   88.0   80.0   77.0   75.0   72.0   72.0   70.0   
1072    205868      33500  109.0  145.0  157.0  164.0  174.0  182.0  187.0   
1073     48258       3500  143.0  151.0  156.0  160.0  164.0  166.0  168.0   
1074     25272      36000  206.0  203.0  194.0   96.0   50.0   38.0   35.0   
1075     32168      70500  195.0  190.0  183.0  174.0  156.0  103.0   81.0   
1076    363063      52000   82.0   93.0  114.0  129.0  114.0  107.0  135.0   
1077     90865      24000   53.0   45.0   33.0   32.0   48.0   90.0  126.0   
1078    113161      29500  1

In [65]:
df2 = df[[str(x) for x in range(3600)]].values

In [93]:
df2.shape

(1089, 3600)

In [95]:
df2 = np.concatenate([df2, 777*np.ones(1089).reshape(1089, 1)], axis=1)

In [ ]:
df2

In [96]:
df2[0:2]

array([[  75.,   81.,   93., ...,   88.,  104.,  777.],
       [ 195.,  189.,  181., ...,  194.,  194.,  777.]])

In [108]:
indices = df2[0:2]
t1 = tf.one_hot(indices, depth=256)  # output: [3 x 3]
t_df2 = tf.constant(df2)
# [[1., 0., 0.],
#  [0., 1., 0.],
#  [0., 0., 1.]]

In [143]:
int(label_idx)

3600

In [153]:
label_idx = tf.shape(t_df2)[1] - 1

xx = tf.slice(t_df2, [0, 0], [-1, label_idx])
yy = tf.slice(t_df2, [0, label_idx], [-1, 1])

In [255]:
zz = tf.nn.sigmoid_cross_entropy_with_logits(
labels=[1.0, 0.0], logits=[-2.0, -55.0])

In [256]:
zzz = tf.reduce_mean(zz)

In [257]:
sess = tf.Session()
t1_, t_df2_, xx_, yy_, zz_, zzz_ = sess.run([t1, t_df2, xx, yy, zz, zzz])

In [258]:
zz_

array([  2.12692809e+00,   1.29958139e-24], dtype=float32)

In [254]:
'{:9.6f}'.format(3.123)

' 3.123000'

In [241]:
zzz_

1.1269281

In [155]:
xx_

array([[  75.,   81.,   93., ...,   81.,   88.,  104.],
       [ 195.,  189.,  181., ...,  193.,  194.,  194.],
       [  27.,   28.,   32., ...,  169.,  141.,   92.],
       ..., 
       [  73.,   66.,   62., ...,  199.,  201.,  204.],
       [  81.,   80.,   78., ...,  186.,  187.,  187.],
       [ 212.,  207.,  206., ...,  209.,  208.,  206.]])

In [156]:
xx_.shape

(1089, 3600)

In [158]:
yy_.shape

(1089, 1)

In [138]:
t1_.shape

(2, 3601, 256)

In [113]:
t_df2

<tf.Tensor 'Const_1:0' shape=(1089, 3601) dtype=float64>

In [111]:
t_df2_

array([[  75.,   81.,   93., ...,   88.,  104.,  777.],
       [ 195.,  189.,  181., ...,  194.,  194.,  777.],
       [  27.,   28.,   32., ...,  141.,   92.,  777.],
       ..., 
       [  73.,   66.,   62., ...,  201.,  204.,  777.],
       [  81.,   80.,   78., ...,  187.,  187.,  777.],
       [ 212.,  207.,  206., ...,  208.,  206.,  777.]])

In [103]:
t1_[0, :, :]

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]], dtype=float32)

In [100]:
t1_[0, :, 75:83]

array([[ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  1.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]], dtype=float32)

In [87]:
t1_[1, :, 189:196]

array([[ 0.,  0.,  0., ...,  0.,  0.,  1.],
       [ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  1.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  1.,  0.],
       [ 0.,  0.,  0., ...,  0.,  1.,  0.]], dtype=float32)

In [88]:
v1 = tf.Variable(t1)

In [91]:
sess.run(tf.global_variables_initializer())
sess.run(v1)

array([[[ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        ..., 
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.]],

       [[ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        ..., 
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.]]], dtype=float32)

In [101]:
t1_

array([[[ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        ..., 
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.]],

       [[ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        ..., 
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.]]], dtype=float32)